#Config file for the serverless application

service: aws-serverless-demo

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable
    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

#define API Gateways
functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      #only need to change names here
      orderTableName: ordersTable
      orderStreamName: order-events
  fulfillOrder:
    handler: handler.fulfillOrder
    events:
    - http:
        path: /order/fulfill
        method: post
    environment:
      #only need to change names here
      orderTableName: ordersTable
      orderStreamName: order-events


#define the AWS resources
resources:
  Resources:
    #Kinesis Stream
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
    #DynamoDB
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "orderID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderID"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST