#Config file for the serverless application
 
service: aws-serverless-demo

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x

  #permissions for using AWS resources
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable
    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - "*" #no particular resource
      Condition:
        StringEquals:
          ses:FromAddress:
            - orderingsystem@sharklasers.com
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:deliveryServiceQueue
        - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:customerServiceQueue

#define API Gateways/lambda functions
functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
    environment:
      #only need to change names here
      orderTableName: ordersTable
      orderStreamName: order-events
  fulfillOrder:
    handler: handler.fulfillOrder
    events:
      - http:
          path: /order/fulfill
          method: post
    environment:
      #only need to change names here
      orderTableName: ordersTable
      orderStreamName: order-events
  deliveredOrder:
    handler: handler.deliveredOrder
    events:
      - http:
          path: /order/delivered
          method: post
    environment:
      region: ${self:provider.region}
      orderTableName: ordersTable
      customerServiceQueue:
        Ref: customerServiceQueue
  notifyExternalParty:
    handler: handler.notifyExternalParty
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    environment:
      region: ${self:provider.region}
      producerEmail: producer@sharklasers.com
      orderingSystemEmail: orderingsystem@sharklasers.com
      deliveryCompanyQueue:
        Ref: deliveryServiceQueue
      orderTableName: ordersTable
  notifyDeliveryCompany:
    handler: handler.notifyDeliveryCompany
    events:
      - sqs:
          arn:
            Fn::GetAtt: #other notation for getting arn
              - deliveryServiceQueue
              - Arn
          batchSize: 1 #how many messages before delivery's notified
  notifyCustomerService:
    handler: handler.notifyCustomerService
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - customerServiceQueue
              - Arn
          batchSize: 1


#define the AWS resources
resources:
  Resources:
    #Kinesis Stream
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
    #DynamoDB
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "orderID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderID"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
    deliveryServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: deliveryServiceQueue
    customerServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: customerServiceQueue